### ISSUE TITLE
Add jclow as an admin

### ISSUE THREAD

**Issue by jclow-sift** [noahgrant/resourcerer#51]
I'd like to be set as an admin on this repo as it largely belongs to me at this point and I will be the main engineer making security updates and the like.

**Comment by noahgrant** [comment]
Hi! I'm actually the maintainer of this repository. I'll handle any security updates or general updates (I also have sole publishing access). Thanks!

**Comment by jclow-sift** [comment]
Oh, sorry, still new and didn't mean to assert ownership unilaterally!

**Comment by noahgrant** [comment]
no problem!
